# serverless.yml

service: my-express-application

provider:
  name: aws
  runtime: nodejs8.10
  apiKeys:
    - dylanapikey2
  stage: v1
  region: us-west-2

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: hello
          method: get
          private: true
  wx:
    handler: index.wxhandler
    events:
      - http:
          path: wx
          method: get
          private: true